import { Model } from 'mongoose';
import { ErrorUtil } from '../../../middleware/ErrorUtil';
import User, { UserType } from '../../auth/models/User';
import { EmailService } from '../email/EmailService';
import Notification from '../model/Notification';
import { ModelKey, ModelMap } from '../../../utils/ModelMap';

export default class UserEvents {
  private readonly modelMap: Record<ModelKey, any> = ModelMap;
  public onPasswordUpdated = async (event: {
    userId: string;
    newPassword: string;
    isAutoGenerated: boolean;
  }) => {
    const { userId, newPassword } = event;
    console.log(`[Notification] Password updated for user ID: ${userId}`);
    // Find the user by ID
    const user = await User.findById(userId);
    if (!user) {
      throw new ErrorUtil('User not found', 404);
    }

    // attempt to locate user's ministry from profileRef's
    const ministry = await this.modelMap['ministry'].findById(
      user?.profileRefs['ministry'] || null
    );

    // Create a notification
    await Notification.insertNotification(
      user._id as any,
      null as any,
      'Password Updated',
      `Your password has been updated successfully.`,
      'user.passwordUpdated',
      user._id as any
    );

    if (event.isAutoGenerated) {
      await EmailService.sendEmail({
        to: user.email,
        subject: 'Your Password Has Been Updated',
        templateId: 'auto-pass-reset',
        data: {
          currentYear: new Date().getFullYear(),
          subject: 'Your Password Has Been Updated',
          password: newPassword,
          name: user.fullName,
          supportEmail: 'support@shepherdcms.org',
          ministryName: ministry ? ministry.name : null,
          logoUrl:
            'https://res.cloudinary.com/wulfdev/image/upload/v1760816772/ShepherdsCMSLogo_p3ipxo.png',
          signInUrl: 'https://auth.shepherdcms.org/login',
        },
      });
    }
  };
}
